import Footer from "@/components/sections/Footer";
import Header from "@/components/sections/Header";
import WhatsAppFloat from "@/components/WhatsAppFloat";
import { ThemeProvider } from "@/providers/theme";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

export const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Lunar Storage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body className={`${inter.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          {children}
          <WhatsAppFloat />
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
